import { NextRequest, NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import path from 'path';

/**
 * GET /api/replay/[series]?year=2024&round=1&session=race
 *
 * Serves pre-computed replay data generated by scripts/fetch_telemetry.py.
 * Falls back to a flag indicating the frontend should use client-side simulation.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ series: string }> }
) {
  const { series } = await params;
  const { searchParams } = new URL(request.url);

  const VALID_SERIES = ['f1', 'f2', 'f3', 'formula-e', 'nascar', 'gt-world-challenge', 'top-fuel'];
  if (!VALID_SERIES.includes(series)) {
    return NextResponse.json({ error: 'Invalid series requested.' }, { status: 400 });
  }

  const year = searchParams.get('year') || '2024';
  const round = searchParams.get('round') || '1';
  const session = searchParams.get('session') || 'race';

  // Prevent path traversal by sanitizing inputs to their basenames
  const cleanYear = path.basename(year);
  const cleanRound = path.basename(round);
  const cleanSession = path.basename(session);

  // Construct the path to the pre-computed JSON
  const filename = `${cleanYear}_round${cleanRound}_${cleanSession}.json`;
  const filePath = path.join(process.cwd(), 'public', 'replay-data', series, filename);
  
  // Extra layer of protection: ensure the resolved path still targets our public directory
  const publicDir = path.join(process.cwd(), 'public', 'replay-data');
  if (!filePath.startsWith(publicDir)) {
    return NextResponse.json({ error: 'Invalid file path.' }, { status: 400 });
  }

  try {
    const data = await readFile(filePath, 'utf-8');
    return new NextResponse(data, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=86400, s-maxage=86400',
      },
    });
  } catch {
    // No pre-computed data — tell frontend to use simulation
    return NextResponse.json(
      {
        source: 'simulation',
        message: `No pre-computed data for ${series} ${year} round ${round} (${session}). Using client-side simulation.`,
        series,
        year: parseInt(year),
        round: parseInt(round),
        session,
      },
      { status: 200 }
    );
  }
}
