import { NextRequest, NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import path from 'path';

/**
 * GET /api/replay/[series]?year=2024&round=1&session=race
 *
 * Serves pre-computed replay data generated by scripts/fetch_telemetry.py.
 * Falls back to a flag indicating the frontend should use client-side simulation.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ series: string }> }
) {
  const { series } = await params;
  const { searchParams } = new URL(request.url);

  const VALID_SERIES = ['f1', 'f2', 'f3', 'formula-e', 'nascar', 'nascar-cup', 'nascar-xfinity', 'nascar-trucks', 'gt-world-challenge', 'top-fuel', 'wec'];
  if (!VALID_SERIES.includes(series)) {
    return NextResponse.json({ error: 'Invalid series requested.' }, { status: 400 });
  }

  const yearParam = searchParams.get('year') || '2024';
  const roundParam = searchParams.get('round') || '1';
  const sessionParam = searchParams.get('session') || 'race';

  const parsedYear = parseInt(yearParam, 10);
  const parsedRound = parseInt(roundParam, 10);
  const safeYear = Number.isInteger(parsedYear) && parsedYear >= 1950 && parsedYear <= 2100 ? parsedYear : 2024;
  const safeRound = Number.isInteger(parsedRound) && parsedRound >= 1 && parsedRound <= 100 ? parsedRound : 1;
  const safeSession = /^[a-zA-Z0-9_-]+$/.test(sessionParam) ? sessionParam.toLowerCase() : 'race';

  // Construct the path to the pre-computed JSON
  const filename = `${safeYear}_round${safeRound}_${safeSession}.json`;
  const filePath = path.resolve(process.cwd(), 'public', 'replay-data', series, filename);
  
  // Extra layer of protection: ensure the resolved path still targets our public directory
  const publicDir = path.resolve(process.cwd(), 'public', 'replay-data');
  if (!filePath.startsWith(publicDir)) {
    return NextResponse.json({ error: 'Invalid file path.' }, { status: 400 });
  }

  try {
    const data = await readFile(filePath, 'utf-8');
    return new NextResponse(data, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=86400, s-maxage=86400',
      },
    });
  } catch {
    // No pre-computed data — tell frontend to use simulation
    return NextResponse.json(
      {
        source: 'simulation',
        message: `No pre-computed data for ${series} ${safeYear} round ${safeRound} (${safeSession}). Using client-side simulation.`,
        series,
        year: safeYear,
        round: safeRound,
        session: safeSession,
      },
      { status: 200 }
    );
  }
}
