import { NextRequest, NextResponse } from 'next/server';
import { readFile } from 'fs/promises';
import path from 'path';

/**
 * GET /api/replay/[series]?year=2024&round=1&session=race
 *
 * Serves pre-computed replay data generated by scripts/fetch_telemetry.py.
 * Falls back to a flag indicating the frontend should use client-side simulation.
 */
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ series: string }> }
) {
  const { series } = await params;
  const { searchParams } = new URL(request.url);

  const year = searchParams.get('year') || '2024';
  const round = searchParams.get('round') || '1';
  const session = searchParams.get('session') || 'race';

  // Construct the path to the pre-computed JSON
  const filename = `${year}_round${round}_${session}.json`;
  const filePath = path.join(process.cwd(), 'public', 'replay-data', series, filename);

  try {
    const data = await readFile(filePath, 'utf-8');
    return new NextResponse(data, {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'public, max-age=86400, s-maxage=86400',
      },
    });
  } catch {
    // No pre-computed data — tell frontend to use simulation
    return NextResponse.json(
      {
        source: 'simulation',
        message: `No pre-computed data for ${series} ${year} round ${round} (${session}). Using client-side simulation.`,
        series,
        year: parseInt(year),
        round: parseInt(round),
        session,
      },
      { status: 200 }
    );
  }
}
